import type { Category, Product, ProductColor, ProductFaq, SiteRoute } from '@/types'

const fabricImages = ['fabrics/hero.jpg', 'fabrics/rose.jpg', 'fabrics/blue.jpg', 'fabrics/emerald.jpg']

const color = (id: string, name: string, hex: string, stockMeters = 12): ProductColor => ({
  id,
  name,
  hex,
  available: stockMeters > 0,
  stockMeters,
})

const faqs = (opacity: string, stretch: string, use: string, care: string): ProductFaq[] => [
  { question: 'هل القماش شفاف؟', answer: opacity },
  { question: 'هل يتمدد بسهولة؟', answer: stretch },
  { question: 'ما أفضل استخدام له؟', answer: use },
  { question: 'كيف تتم العناية به؟', answer: care },
]

export const fallbackCategories: Category[] = [
  {
    id: 'embroidered',
    slug: 'embroidered',
    name: 'مطرز',
    description: 'تطريز بارز وخيوط فاخرة',
    image: 'fabrics/rose.jpg',
    accent: '#8f4766',
  },
  {
    id: 'plain',
    slug: 'plain',
    name: 'سادة',
    description: 'ألوان هادئة للاستخدام اليومي',
    image: 'fabrics/blue.jpg',
    accent: '#42647b',
  },
  {
    id: 'stretch',
    slug: 'stretch',
    name: 'مطاطي',
    description: 'سبانديكس وتويل بمرونة مريحة',
    image: 'fabrics/emerald.jpg',
    accent: '#34715e',
  },
  {
    id: 'sequined',
    slug: 'sequined',
    name: 'ترتر ولمّاع',
    description: 'بريق وحركة للحفلات',
    image: 'fabrics/hero.jpg',
    accent: '#8d2b4f',
  },
  {
    id: 'patterned',
    slug: 'patterned',
    name: 'مزخرف',
    description: 'نقوش جاكار وتطريز منظم',
    image: 'fabrics/rose.jpg',
    accent: '#8c5c82',
  },
]

export const fallbackProducts: Product[] = [
  {
    id: 'p1',
    slug: 'krip-spandeks-naseem',
    name: 'كريب سبانديكس ناعم',
    type: 'سبانديكس / مطاطي',
    categoryId: 'stretch',
    description: 'كريب مرن بملمس ناعم ومطفأ، يتمدد في الاتجاهين ويعيد شكله بسهولة. مناسب للفساتين المحتشمة والأبراق والقطع التي تحتاج راحة طوال اليوم.',
    price: 7500,
    image: 'fabrics/emerald.jpg',
    images: ['fabrics/emerald.jpg', 'fabrics/blue.jpg', 'fabrics/hero.jpg'],
    colors: [
      color('black', 'أسود', '#171717'),
      color('wine', 'خمري', '#681d35'),
      color('navy', 'كحلي', '#1b2c4c'),
      color('camel', 'كاميل', '#bd9668'),
    ],
    specs: {
      composition: '95% بوليستر، 5% إيلاستان',
      width: '150 سم',
      weight: '200 غ/م²',
      stretch: 'مطاطي جداً في الاتجاهين',
      isStretch: true,
      opacity: 'غير شفاف تماماً',
      finish: 'ناعم مطفأ',
      care: 'غسيل يدوي بماء فاتر، لا تجفيف بالمجفف',
      use: 'فساتين، أبراق، تنانير، بناطيل رسمية',
    },
    faqs: faqs('غير شفاف تماماً', 'مطاطي جداً في الاتجاهين', 'فساتين وأبراق وتنانير', 'غسيل يدوي بماء فاتر، لا تجفيف بالمجفف'),
    isNew: true,
    isFeatured: true,
    stockMeters: 18,
    createdAt: '2026-08-20',
  },
  {
    id: 'p2',
    slug: 'taffeta-mtarzath-dhahabiya',
    name: 'تافتا مطرزة ذهبية',
    type: 'مطرز فاخر',
    categoryId: 'embroidered',
    description: 'تافتا فاخرة بتطريز ذهبي بارز ونسيج محكم. تمنح المناسبات والعباءات ثباتاً واضحاً ولمعة هادئة تحت الإضاءة.',
    price: 18000,
    compareAtPrice: 19500,
    image: 'fabrics/rose.jpg',
    images: ['fabrics/rose.jpg', 'fabrics/hero.jpg', 'fabrics/blue.jpg'],
    colors: [
      color('black-gold', 'أسود ذهبي', '#1d1b15'),
      color('red-gold', 'أحمر ذهبي', '#7d2525'),
      color('emerald-gold', 'زمردي ذهبي', '#214d3b'),
    ],
    specs: {
      composition: '100% بوليستر',
      width: '130 سم',
      weight: '310 غ/م²',
      stretch: 'غير مطاطي',
      isStretch: false,
      opacity: 'غير شفاف',
      finish: 'تطريز ذهبي لامع',
      care: 'تنظيف جاف، حفظ جاف بعيداً عن الرطوبة',
      use: 'عبايات مناسبات، فساتين سهرة، قطع احتفالية',
    },
    faqs: faqs('غير شفاف', 'غير مطاطي ويحافظ على شكله', 'العبايات وملابس المناسبات', 'تنظيف جاف، حفظ جاف بعيداً عن الرطوبة'),
    isNew: false,
    isFeatured: true,
    stockMeters: 9,
    createdAt: '2026-05-10',
  },
  {
    id: 'p3',
    slug: 'terter-hologram',
    name: 'ترتر هولوغرام راقٍ',
    type: 'ترتر ولمّاع',
    categoryId: 'sequined',
    description: 'ترتر متعدد الألوان يغيّر انعكاسه مع الحركة. مثالي لتضيف بريقاً واضحاً إلى فساتين الحفلات وتفاصيل السهرة.',
    price: 12500,
    image: 'fabrics/hero.jpg',
    images: ['fabrics/hero.jpg', 'fabrics/blue.jpg', 'fabrics/rose.jpg'],
    colors: [
      color('silver', 'فضي', '#c5c7ca', 4),
      color('gold', 'ذهبي', '#d4ad3b', 2),
      color('rose-gold', 'روز ذهبي', '#b56c78', 3),
    ],
    specs: {
      composition: '90% بوليستر، 10% نايلون',
      width: '140 سم',
      weight: '190 غ/م²',
      stretch: 'مرونة خفيفة باتجاه واحد',
      isStretch: false,
      opacity: 'غير شفاف',
      finish: 'ترتر هولوغرام لامع',
      care: 'تنظيف جاف أو غسيل يدوي لطيف',
      use: 'فساتين الحفلات، الأزياء المسائية، إكسسوارات',
    },
    faqs: faqs('غير شفاف', 'مرونة خفيفة باتجاه واحد، وليس مطاطياً كاملاً', 'الحفلات وفساتين السهرة', 'تنظيف جاف أو غسيل يدوي لطيف'),
    isNew: true,
    isFeatured: true,
    stockMeters: 2.5,
    createdAt: '2026-09-01',
  },
  {
    id: 'p4',
    slug: 'linen-cotton-soft',
    name: 'لينن قطن ناعم',
    type: 'سادة طبيعي',
    categoryId: 'plain',
    description: 'مزيج طبيعي يتنفس ويمنح إطلالة يومية هادئة. مناسب للفساتين الصيفية والقمصان مع سهولة في الثني والتنسيق.',
    price: 8500,
    image: 'fabrics/blue.jpg',
    images: ['fabrics/blue.jpg', 'fabrics/rose.jpg', 'fabrics/emerald.jpg'],
    colors: [
      color('beige', 'بيج', '#d1b695'),
      color('white', 'أبيض', '#f4f0e9'),
      color('gray', 'رمادي', '#999590'),
      color('sage', 'أخضر مريمي', '#81977f', 0),
    ],
    specs: {
      composition: '55% لينن، 45% قطن',
      width: '145 سم',
      weight: '165 غ/م²',
      stretch: 'غير مطاطي',
      isStretch: false,
      opacity: 'شفاف قليلاً، يوصى ببطانة',
      finish: 'نسيج طبيعي ناعم',
      care: 'غسيل بارد أو يدوي، كوي بحرارة متوسطة',
      use: 'فساتين صيفية، قمصان، بناطيل، أبراق خفيفة',
    },
    faqs: faqs('شفاف قليلاً، يوصى ببطانة', 'غير مطاطي', 'الفساتين الصيفية والقمصان', 'غسيل بارد أو يدوي، كوي بحرارة متوسطة'),
    isNew: false,
    isFeatured: true,
    stockMeters: 14,
    createdAt: '2026-04-18',
  },
  {
    id: 'p5',
    slug: 'twill-spandeks-mat',
    name: 'تويل سبانديكس مطفأ',
    type: 'سبانديكس / مطاطي',
    categoryId: 'stretch',
    description: 'تويل مرن بوزن متوسط وحواف نظيفة. يمنح البنطلونات والتنانير المحتشمة قواماً منظماً مع سهولة في الخياطة.',
    price: 9000,
    image: 'fabrics/blue.jpg',
    images: ['fabrics/blue.jpg', 'fabrics/hero.jpg', 'fabrics/emerald.jpg'],
    colors: [
      color('black', 'أسود', '#0c0c0d'),
      color('camel', 'كاميل', '#bd9769'),
      color('navy', 'كحلي', '#1c2c4c'),
      color('brown', 'بني', '#5a3d2b', 0),
    ],
    specs: {
      composition: '70% بوليستر، 25% رايون، 5% إيلاستان',
      width: '150 سم',
      weight: '250 غ/م²',
      stretch: 'مطاطي باتجاه واحد',
      isStretch: true,
      opacity: 'غير شفاف تماماً',
      finish: 'تويل مطفأ',
      care: 'غسيل بارد، لا تجفيف بالمجفف',
      use: 'بناطيل، تنانير، سترات، ملابس رسمية',
    },
    faqs: faqs('غير شفاف تماماً', 'مطاطي باتجاه واحد', 'البناطيل والتنانير والملابس الرسمية', 'غسيل بارد، لا تجفيف بالمجفف'),
    isNew: false,
    isFeatured: true,
    stockMeters: 11,
    createdAt: '2026-03-05',
  },
  {
    id: 'p6',
    slug: 'jacquard-fancy',
    name: 'جاكار مزهر فاخر',
    type: 'منسوجات مزخرفة',
    categoryId: 'patterned',
    description: 'جاكار بنقوش محبوكة وعمق بصري واضح. يعطي القطع الرسمية حضوراً خاصاً من دون أن يحتاج إلى تفاصيل إضافية كثيرة.',
    price: 15000,
    image: 'fabrics/rose.jpg',
    images: ['fabrics/rose.jpg', 'fabrics/blue.jpg', 'fabrics/hero.jpg'],
    colors: [
      color('white-gold', 'أبيض ذهبي', '#efe6cf'),
      color('blush', 'وردي ناعم', '#e6c6cc'),
      color('black-silver', 'أسود فضي', '#1b1b1f'),
      color('royal-blue', 'أزرق ملكي', '#293c78', 0),
    ],
    specs: {
      composition: '60% بوليستر، 40% رايون',
      width: '140 سم',
      weight: '280 غ/م²',
      stretch: 'غير مطاطي',
      isStretch: false,
      opacity: 'غير شفاف',
      finish: 'نقوش جاكار بارزة',
      care: 'تنظيف جاف فقط',
      use: 'فساتين فاخرة، عبايات مناسبات، قطع رسمية',
    },
    faqs: faqs('غير شفاف', 'غير مطاطي', 'الفساتين الفاخرة والمناسبات', 'تنظيف جاف فقط'),
    isNew: true,
    isFeatured: true,
    stockMeters: 6.5,
    createdAt: '2026-08-28',
  },
  {
    id: 'p7',
    slug: 'satin-solid-soft',
    name: 'ساتان سادة بلمعة هادئة',
    type: 'ساتان',
    categoryId: 'plain',
    description: 'ساتان بلمعة مضبوطة وانسدال ناعم. خيار متوازن بين الفخامة وسهولة الاستخدام في المناسبات والفساتين المسائية.',
    price: 6900,
    image: 'fabrics/hero.jpg',
    images: ['fabrics/hero.jpg', 'fabrics/rose.jpg', 'fabrics/blue.jpg'],
    colors: [
      color('emerald', 'زمردي', '#1c6c55'),
      color('plum', 'برقوقي', '#57324f'),
      color('silver', 'فضي', '#b8bdc0'),
    ],
    specs: {
      composition: '100% بوليستر',
      width: '150 سم',
      weight: '180 غ/م²',
      stretch: 'غير مطاطي',
      isStretch: false,
      opacity: 'غير شفاف',
      finish: 'ساتان بلمعة هادئة',
      care: 'غسيل يدوي، لا تعصر القماش',
      use: 'فساتين سهرة، بلوزات، تنانير مناسبات',
    },
    faqs: faqs('غير شفاف', 'غير مطاطي', 'الفساتين المسائية والمناسبات', 'غسيل يدوي، لا تعصر القماش'),
    isNew: false,
    isFeatured: false,
    stockMeters: 16,
    createdAt: '2026-02-14',
  },
  {
    id: 'p8',
    slug: 'crepe-embroidered-plum',
    name: 'كريب مطرز برقوقي',
    type: 'كريب مطرز',
    categoryId: 'embroidered',
    description: 'كريب خفيف بتطريز هندسي دقيق يترك مساحة واسعة للتصميم. مناسب للفساتين اليومية المميزة والقطع القريبة من ذوقك.',
    price: 11200,
    image: 'fabrics/rose.jpg',
    images: ['fabrics/rose.jpg', 'fabrics/emerald.jpg', 'fabrics/hero.jpg'],
    colors: [
      color('plum', 'برقوقي', '#613c5b'),
      color('rose', 'وردي غباري', '#c49a9d'),
      color('olive', 'زيتوني', '#657055', 0),
    ],
    specs: {
      composition: '92% بوليستر، 8% إيلاستان',
      width: '145 سم',
      weight: '195 غ/م²',
      stretch: 'مرونة خفيفة جداً',
      isStretch: false,
      opacity: 'غير شفاف',
      finish: 'تطريز هندسي باهت',
      care: 'غسيل بارد، قلب القطعة قبل التجفيف',
      use: 'فساتين، بلوزات، قطع يومية مميزة',
    },
    faqs: faqs('غير شفاف', 'مرونة خفيفة جداً، وليس مطاطياً كاملاً', 'الفساتين والبلوزات اليومية', 'غسيل بارد، قلب القطعة قبل التجفيف'),
    isNew: true,
    isFeatured: false,
    stockMeters: 7,
    createdAt: '2026-09-06',
  },
  {
    id: 'p9',
    slug: 'cotton-twill-sand',
    name: 'تويل قطني رملي',
    type: 'تويل قطني',
    categoryId: 'plain',
    description: 'تويل قطني بلون محايد وبنية واضحة. يتحمل الاستخدام المتكرر ويمنح البناطيل والقطع اليومية مظهراً نظيفاً.',
    price: 9900,
    image: 'fabrics/blue.jpg',
    images: ['fabrics/blue.jpg', 'fabrics/hero.jpg', 'fabrics/rose.jpg'],
    colors: [
      color('sand', 'رملي', '#c8ad86'),
      color('stone', 'حجري', '#a59b8f'),
      color('ink', 'حبري', '#32363d'),
    ],
    specs: {
      composition: '80% قطن، 20% بوليستر',
      width: '145 سم',
      weight: '240 غ/م²',
      stretch: 'غير مطاطي',
      isStretch: false,
      opacity: 'غير شفاف',
      finish: 'نسيج قطري واضح',
      care: 'غسيل آلة على برنامج قطن، كوي متوسط',
      use: 'بناطيل، تنانير، قمصان، حقائب',
    },
    faqs: faqs('غير شفاف', 'غير مطاطي', 'البناطيل والقمصان والحقائب', 'غسيل آلة على برنامج قطن، كوي متوسط'),
    isNew: false,
    isFeatured: true,
    stockMeters: 0,
    createdAt: '2026-01-12',
  },
  {
    id: 'p10',
    slug: 'velvet-cobalt-deep',
    name: 'مخمل أزرق عميق',
    type: 'مخمل',
    categoryId: 'plain',
    description: 'مخمل بويبة ناعمة وعمق لوني واضح. مناسب للجاكيتات والفساتين التي تحتاج إلى حضور دافئ ومترف.',
    price: 14200,
    image: 'fabrics/blue.jpg',
    images: ['fabrics/blue.jpg', 'fabrics/hero.jpg', 'fabrics/rose.jpg'],
    colors: [
      color('cobalt', 'أزرق كوبالت', '#244c82'),
      color('wine', 'خمري', '#61283b'),
      color('forest', 'أخضر داكن', '#284b42', 0),
    ],
    specs: {
      composition: '88% بوليستر، 12% فيسكوز',
      width: '150 سم',
      weight: '330 غ/م²',
      stretch: 'غير مطاطي',
      isStretch: false,
      opacity: 'غير شفاف',
      finish: 'وبرة مخملية ناعمة',
      care: 'تنظيف جاف أو فرش ناعم',
      use: 'جاكيتات، عبايات، فساتين شتوية',
    },
    faqs: faqs('غير شفاف', 'غير مطاطي', 'الجاكيتات والفساتين الموسمية', 'تنظيف جاف أو فرش ناعم'),
    isNew: false,
    isFeatured: true,
    stockMeters: 4,
    createdAt: '2026-06-01',
  },
  {
    id: 'p11',
    slug: 'linen-blend-sage',
    name: 'لينن مخلوط بالأخضر',
    type: 'لينن مخلوط',
    categoryId: 'plain',
    description: 'نسيج متوازن فيه ملمس اللينن وهشاشة قطن قابلة للتنفس. لون مريمي هادئ للمناسبات الصيفية البسيطة.',
    price: 10500,
    image: 'fabrics/emerald.jpg',
    images: ['fabrics/emerald.jpg', 'fabrics/blue.jpg', 'fabrics/rose.jpg'],
    colors: [
      color('sage', 'أخضر مريمي', '#87977e'),
      color('oat', 'شوفان', '#d1c1a7'),
      color('terracotta', 'طيني', '#a96552'),
    ],
    specs: {
      composition: '60% لينن، 40% قطن',
      width: '145 سم',
      weight: '175 غ/م²',
      stretch: 'غير مطاطي',
      isStretch: false,
      opacity: 'نصف شفاف',
      finish: 'نسيج طبيعي مطفي',
      care: 'غسيل يدوي، تجفيف في الظل',
      use: 'فساتين صيفية، عباءات خفيفة، قمصان',
    },
    faqs: faqs('نصف شفاف، يفضل استخدام بطانة', 'غير مطاطي', 'الفساتين الصيفية والعباءات الخفيفة', 'غسيل يدوي، تجفيف في الظل'),
    isNew: true,
    isFeatured: false,
    stockMeters: 5,
    createdAt: '2026-09-10',
  },
]

export const fallbackRoutes: SiteRoute[] = [
  { id: 'home', label: 'الرئيسية', path: '/', header: true },
  { id: 'catalog', label: 'الأقمشة', path: '/catalog', header: true },
  { id: 'new', label: 'وصل حديثاً', path: '/catalog?sort=newest', header: true },
  { id: 'favorites', label: 'المفضلة', path: '/favorites', header: false },
  { id: 'about', label: 'من نحن', path: '/about', header: true },
  { id: 'guide', label: 'دليل الأقمشة', path: '/fabric-guide', header: true },
  { id: 'contact', label: 'تواصلي معنا', path: '/contact', header: false },
  { id: 'tracking', label: 'تتبع الطلب', path: '/order-tracking', header: false },
  { id: 'policies', label: 'السياسات', path: '/policies', header: false },
]

export const governorates = [
  'بغداد', 'البصرة', 'نينوى', 'أربيل', 'النجف', 'كربلاء', 'الأنبار', 'ديالى',
  'كركوك', 'صلاح الدين', 'واسط', 'بابل', 'ذي قار', 'ميسان', 'المثنى', 'القادسية', 'دهوك', 'السليمانية',
]

export const guideQuestions: ProductFaq[] = [
  { question: 'كيف أختار القماش المناسب؟', answer: 'ابدئي من الاستخدام: القماش اليومي يحتاج خامة خفيفة ومريحة، بينما المناسبات قد تحتاج وزناً وثباتاً ولمعة. راجعي المرونة والشفافية والعرض قبل الشراء.' },
  { question: 'ما الفرق بين المطاطي وغير المطاطي؟', answer: 'المطاطي يحتوي على نسبة إيلاستان أو سبانديكس، فيتمدد ويعود إلى شكله. غير المطاطي أكثر ثباتاً ومناسب للقطع ذات البنية الواضحة. التسمية في المتجر تعتمد على المرونة الفعلية للتصميم.' },
  { question: 'كيف أعرف العرض المناسب؟', answer: 'العرض هو قياس القماش من حافة إلى حافة، وهو مكتوب في مواصفات كل منتج. كلما زاد العرض قل القماش المطلوب للقطعة الواحدة.' },
  { question: 'كيف أحدد الكمية؟', answer: 'للقطعة البسيجة غالباً تحتاجين بين 2 و2.5 متر، وللعباءة بين 3 و4 أمتار. أضيفي هامشاً بسيطاً للقص والخياطة، ويمكن الطلب بنصف متر.' },
  { question: 'كيف أقرأ وصف اللون؟', answer: 'الصور تمثل نموذجاً بصرياً للخامة. قارني اللون مع الإضاءة المحيطة والقطع المشابهة، وتواصلي معنا إذا كان اللون حساساً لمشروعك.' },
]

export const trustItems = [
  { title: 'توصيل لكل العراق', description: 'جميع المحافظات', icon: 'truck' },
  { title: 'شحن دولي', description: 'عند توفر الشحنة', icon: 'globe' },
  { title: 'دعم عبر واتساب', description: 'قبل وبعد الطلب', icon: 'message' },
  { title: 'اختيار واعٍ', description: 'مواصفات واضحة', icon: 'check' },
] as const

export const homeStory = {
  title: 'أقمشة تستحق الاختيار الواثق',
  text: 'إيفا ستور مساحة عراقية تجمع بين تشكيلة متنوعة وشرح واضح للّمس والامتداد واللون، لتسهيل قرارك قبل طلب المتر.',
}

export { fabricImages }
