import type { Category, Product, ProductColor, ProductFaq, SiteRoute } from '@/types'

const color = (id: string, name: string, hex: string, stock = 10): ProductColor => ({
  id,
  name,
  hex,
  available: stock > 0,
  stock,
})

const faqs = (power: string, warranty: string, use: string, care: string): ProductFaq[] => [
  { question: 'كم استهلاك الطاقة؟', answer: power },
  { question: 'ما مدة الضمان؟', answer: warranty },
  { question: 'ما أفضل استخدام لهذا الجهاز؟', answer: use },
  { question: 'كيف أنظف الجهاز وأحافظ عليه؟', answer: care },
]

export const fallbackCategories: Category[] = [
  {
    id: 'tvs',
    slug: 'tvs',
    name: 'التلفزيونات',
    description: 'شاشات ذكية بمقاسات متعددة',
    image: 'products/category-tvs.webp',
    accent: '#16233f',
  },
  {
    id: 'ac',
    slug: 'ac',
    name: 'المكيفات',
    description: 'سبليت وإنفرتر بقدرات مختلفة',
    image: 'products/category-ac.webp',
    accent: '#1e5f8f',
  },
  {
    id: 'wash',
    slug: 'wash',
    name: 'الغسالات',
    description: 'أوتوماتيك ونصف أوتوماتيك',
    image: 'products/category-wash.webp',
    accent: '#4a5f8c',
  },
  {
    id: 'fridge',
    slug: 'fridge',
    name: 'الثلاجات',
    description: 'بابين وأربعة أبواب باستهلاك منخفض',
    image: 'products/category-fridge.webp',
    accent: '#2b6b7a',
  },
  {
    id: 'kitchen',
    slug: 'kitchen',
    name: 'أجهزة المطبخ',
    description: 'غلايات وخلاطات وأفران ميكروويف',
    image: 'products/category-kitchen.webp',
    accent: '#e0357f',
  },
  {
    id: 'fans',
    slug: 'fans',
    name: 'المراوح والدفايات',
    description: 'مراوح سقف وعمود ودفايات موسمية',
    image: 'products/category-fans.webp',
    accent: '#5a4f8c',
  },
]

export const fallbackProducts: Product[] = [
  {
    id: 'p1',
    slug: 'samsung-crystal-55',
    name: 'تلفزيون سامسونج كريستال 55 بوصة',
    type: 'تلفزيون ذكي',
    categoryId: 'tvs',
    description: 'شاشة UHD بدقة 4K مع تقنية Crystal Color تمنح الألوان عمقاً واضحاً، ونظام Tizen لتشغيل التطبيقات والبث المباشر بسلاسة.',
    price: 1195000,
    image: 'products/samsung-crystal-55.webp',
    images: ['products/samsung-crystal-55.webp', 'products/tv-gallery-1.webp', 'products/tv-gallery-2.webp'],
    colors: [
      color('black', 'أسود', '#171717'),
      color('silver', 'فضي', '#c9ccce'),
    ],
    specs: {
      brand: 'سامسونج',
      power: '110 واط',
      capacity: '55 بوصة (139 سم)',
      size: '139 × 79 × 8 سم',
      weight: '13.6 كجم',
      warranty: 'سنتان',
      finish: 'إطار معدني نحيف',
      use: 'غرف المعيشة والصالات',
    },
    faqs: faqs('110 واط في التشغيل، وأقل من 0.5 واط في وضع الاستعداد', 'سنتان على قطع الغيار ومحرك التلفزيون', 'مشاهدة الأفلام والقنوات وتطبيقات البث في غرفة المعيشة', 'مسح الشاشة بقطعة قماش ميكروفايبر جاف، وتجنّب الرذاذ الماء المباشر'),
    isNew: true,
    isFeatured: true,
    unit: 'قطعة',
    stock: 12,
    createdAt: '2026-09-18',
  },
  {
    id: 'p2',
    slug: 'lg-uhd-43',
    name: 'تلفزيون إل جي UHD 43 بوصة',
    type: 'تلفزيون ذكي',
    categoryId: 'tvs',
    description: 'شاشة 4K بحجم مناسب للغرف المتوسطة مع مُحسّن AI وسماعات مدمجة، ودعم HDR10 لتفاصيل أفضل في المشاهد المظلمة.',
    price: 745000,
    image: 'products/lg-uhd-43.webp',
    images: ['products/lg-uhd-43.webp', 'products/tv-gallery-2.webp', 'products/tv-gallery-1.webp'],
    colors: [
      color('black', 'أسود', '#131313'),
      color('gray', 'رمادي داكن', '#3a3d40'),
    ],
    specs: {
      brand: 'إل جي',
      power: '90 واط',
      capacity: '43 بوصة (109 سم)',
      size: '109 × 63 × 8 سم',
      weight: '9.8 كجم',
      warranty: 'سنتان',
      finish: 'إطار رمادي مطفي',
      use: 'غرف النوم والمكاتب',
    },
    faqs: faqs('90 واط في التشغيل، وأقل من 0.5 واط في وضع الاستعداد', 'سنتان شاملة قطع الغيار', 'غرف النوم والمكاتب والمساحات المتوسطة', 'إطفاء الجهاز من الزر وليس من الكهرباء، وتنظيف الإطار بقطعة قماش ناعمة'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 9,
    createdAt: '2026-06-12',
  },
  {
    id: 'p3',
    slug: 'tcl-qled-65',
    name: 'تلفزيون تي سي إل QLED 65 بوصة',
    type: 'تلفزيون QLED',
    categoryId: 'tvs',
    description: 'شاشة كبيرة بتقنية Quantum Dot لألوان أكثر حيوية، مع تأخير منخفض في وضع الألعاب ومدخل HDMI 2.1.',
    price: 1650000,
    compareAtPrice: 1780000,
    image: 'products/tcl-qled-65.webp',
    images: ['products/tcl-qled-65.webp', 'products/tv-gallery-1.webp', 'products/tv-gallery-2.webp'],
    colors: [
      color('black', 'أسود', '#101014'),
      color('champagne', 'شمبانيا', '#cdb9a4'),
    ],
    specs: {
      brand: 'تي سي إل',
      power: '150 واط',
      capacity: '65 بوصة (165 سم)',
      size: '165 × 95 × 9 سم',
      weight: '21.5 كجم',
      warranty: 'سنتان',
      finish: 'إطار معدني رفيع',
      use: 'غرف المعيشة الواسعة',
    },
    faqs: faqs('150 واط في التشغيل، وأقل من 0.5 واط في وضع الاستعداد', 'سنتان، والشاشة ثلاث سنوات', 'غرف المعيشة الواسعة والألعاب والبث بجودة 4K', 'تنظيف الشاشة بقطعة قماش ميكروفايبر رطبة قليلاً ومن دون ضغط'),
    isNew: true,
    isFeatured: true,
    unit: 'قطعة',
    stock: 6,
    createdAt: '2026-09-05',
  },
  {
    id: 'p4',
    slug: 'gree-split-12',
    name: 'مكيف جري سبليت 12 ألف وحدة',
    type: 'مكيف سبليت',
    categoryId: 'ac',
    description: 'مكيف سبليت بتبريد سريع وتشغيل هادئ، مع فلتر قابل للتنظيف وشطف تلقائي يمنع رطوبة المكثف بعد الإيقاف.',
    price: 685000,
    image: 'products/gree-split-12.webp',
    images: ['products/gree-split-12.webp', 'products/ac-gallery-1.webp', 'products/ac-gallery-2.webp'],
    colors: [
      color('white', 'أبيض', '#f2f2f2'),
    ],
    specs: {
      brand: 'جري',
      power: '1050 واط',
      capacity: '12 ألف وحدة (34 م²)',
      size: '80 × 28 × 20 سم',
      weight: '9.5 كجم',
      warranty: 'سنة كاملة',
      finish: 'أبيض لامع',
      use: 'غرف النوم حتى 34 متر مربع',
    },
    faqs: faqs('1050 واط، ويتغير مع درجة الحرارة المضبوطة', 'سنة على قطع الغيار وست سنوات على ضاغط الهواء', 'غرف النوم والمساحات حتى 34 متر مربع', 'تنظيف الفلتر كل أسبوعين، وغسل الوحدة الخارجية مرتين سنوياً'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 14,
    createdAt: '2026-05-22',
  },
  {
    id: 'p5',
    slug: 'general-inverter-18',
    name: 'مكيف إنفرتر جنرال 18 ألف وحدة',
    type: 'مكيف إنفرتر',
    categoryId: 'ac',
    description: 'تقنية إنفرتر تضبط سرعة الضاغط حسب الحرارة المطلوبة، فتقلّل الاستهلاك وتحافظ على ثبات الحرارة طوال الليل.',
    price: 1150000,
    image: 'products/general-inverter-18.webp',
    images: ['products/general-inverter-18.webp', 'products/ac-gallery-2.webp', 'products/ac-gallery-1.webp'],
    colors: [
      color('white', 'أبيض', '#f4f4f4'),
      color('gray', 'رمادي فاتح', '#d7d7d7'),
    ],
    specs: {
      brand: 'جنرال',
      power: '1450 واط',
      capacity: '18 ألف وحدة (50 م²)',
      size: '100 × 33 × 24 سم',
      weight: '12.8 كجم',
      warranty: 'سنة كاملة',
      finish: 'أبيض مطفي',
      use: 'غرف المعيشة حتى 50 متر مربع',
    },
    faqs: faqs('1450 واط، وأقل بنحو 40% مقارنة بالسبليت العادي في الاستخدام الطويل', 'سنة كاملة، وخمس سنوات على ضاغط الإنفرتر', 'غرف المعيشة والصالات حتى 50 متر مربع', 'تنظيف الفلتر شهرياً وضبط الحرارة على 24–26 درجة للاستهلاك الأقل'),
    isNew: true,
    isFeatured: true,
    unit: 'قطعة',
    stock: 8,
    createdAt: '2026-09-12',
  },
  {
    id: 'p6',
    slug: 'carrier-split-9',
    name: 'مكيف كاريير سبليت 9 آلاف وحدة',
    type: 'مكيف سبليت',
    categoryId: 'ac',
    description: 'مكيف اقتصادي بقدرات مناسبة للغرف الصغيرة، مع وضع الليل الهادئ وتشغيل مستقر على الكهرباء المتقطعة.',
    price: 545000,
    image: 'products/carrier-split-9.webp',
    images: ['products/carrier-split-9.webp', 'products/ac-gallery-1.webp', 'products/ac-gallery-2.webp'],
    colors: [
      color('white', 'أبيض', '#f0f0f0'),
    ],
    specs: {
      brand: 'كاريير',
      power: '820 واط',
      capacity: '9 آلاف وحدة (25 م²)',
      size: '72 × 25 × 19 سم',
      weight: '8.2 كجم',
      warranty: 'سنة كاملة',
      finish: 'أبيض لامع',
      use: 'الغرف الصغيرة حتى 25 متر مربع',
    },
    faqs: faqs('820 واط في التشغيل العادي', 'سنة على قطع الغيار وخمس سنوات على الضاغط', 'الغرف الصغيرة والمكاتب حتى 25 متر مربع', 'تنظيف الفلتر كل أسبوعين واستخدام شطف تلقائي قبل الإيقاف'),
    isNew: false,
    isFeatured: false,
    unit: 'قطعة',
    stock: 11,
    createdAt: '2026-04-08',
  },
  {
    id: 'p7',
    slug: 'samsung-wash-8',
    name: 'غسالة سامسونج أوتوماتيك 8 كجم',
    type: 'غسالة أوتوماتيك',
    categoryId: 'wash',
    description: 'غسالة فتحة أمامية بمحرك ديجيتال إنفرتر هادئ وبرنامج EcoBubble يذيب المسحوق قبل الغسيل لتوفير الطاقة.',
    price: 1050000,
    image: 'products/samsung-wash-8.webp',
    images: ['products/samsung-wash-8.webp', 'products/wash-gallery-1.webp', 'products/wash-gallery-2.webp'],
    colors: [
      color('white', 'أبيض', '#f3f3f3'),
      color('silver', 'فضي', '#cfd2d4'),
    ],
    specs: {
      brand: 'سامسونج',
      power: '2000 واط (تسخين)',
      capacity: '8 كجم غسيل',
      size: '60 × 85 × 45 سم',
      weight: '62 كجم',
      warranty: 'سنتان',
      finish: 'أبيض مع باب كريستال',
      use: 'عائلات من 4 إلى 6 أفراد',
    },
    faqs: faqs('2000 واط في دورات التسخين، وتشتغل الغسالة على 220 فولت عادي', 'سنتان شاملة، وعشر سنوات على محرك الديجيتال إنفرتر', 'غسيل ملابس العائلة اليومية حتى 8 كجم في الدورة', 'تنظيف درج المسحق شهرياً وتشغيل دورة تنظيف بابم أعلى مرة كل شهرين'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 7,
    createdAt: '2026-07-01',
  },
  {
    id: 'p8',
    slug: 'lg-twinwash-7',
    name: 'غسالة إل جي توين واش 7 كجم',
    type: 'غسالة أوتوماتيك',
    categoryId: 'wash',
    description: 'غسالة بمحرك إنفرتر مباشر وبرامج AI DD تختار الحركة المناسبة لنوع القماش، مع دعم التحكم عبر التطبيق.',
    price: 895000,
    image: 'products/lg-twinwash-7.webp',
    images: ['products/lg-twinwash-7.webp', 'products/wash-gallery-2.webp', 'products/wash-gallery-1.webp'],
    colors: [
      color('white', 'أبيض', '#f1f1f1'),
      color('gray', 'رمادي فاتح', '#d9d9d9'),
    ],
    specs: {
      brand: 'إل جي',
      power: '2000 واط (تسخين)',
      capacity: '7 كجم غسيل',
      size: '60 × 85 × 46 سم',
      weight: '57 كجم',
      warranty: 'سنتان',
      finish: 'أبيض مع باب دائري',
      use: 'الأسر من 3 إلى 5 أفراد',
    },
    faqs: faqs('2000 واط في دورات التسخين و60 واط في الدورات الباردة', 'سنتان، وعشر سنوات على المحرك المباشر', 'غسيل الملابس اليومية والقطنية حتى 7 كجم', 'مسح حافة المطاطية بعد كل غسيل وترك باب الغسالة مفتوحاً للتهوية'),
    isNew: true,
    isFeatured: true,
    unit: 'قطعة',
    stock: 10,
    createdAt: '2026-09-08',
  },
  {
    id: 'p9',
    slug: 'haier-wash-6',
    name: 'غسالة هاير نصف أوتوماتيك 6 كجم',
    type: 'غسالة نصف أوتوماتيك',
    categoryId: 'wash',
    description: 'غسالة اقتصادية بتصميم بسيط وتشغيل سهل، مناسبة للاستخدام اليومي وللأماكن ذات التيار المتقطع.',
    price: 520000,
    image: 'products/haier-wash-6.webp',
    images: ['products/haier-wash-6.webp', 'products/wash-gallery-1.webp', 'products/wash-gallery-2.webp'],
    colors: [
      color('white', 'أبيض', '#efefef'),
      color('blue', 'أزرق فاتح', '#a8c6e0'),
    ],
    specs: {
      brand: 'هاير',
      power: '1200 واط (تسخين)',
      capacity: '6 كجم غسيل',
      size: '52 × 90 × 54 سم',
      weight: '33 كجم',
      warranty: 'سنة كاملة',
      finish: 'أبيض مع غطاء علوي',
      use: 'الأسر الصغيرة والاستخدام اليومي',
    },
    faqs: faqs('1200 واط في دورات التسخين', 'سنة كاملة على قطع الغيار والمحرك', 'غسيل يومي حتى 6 كجم مع فصل التصريف اليدوي', 'تفريغ خزانة العصر بعد كل غسيل وتنظيف الفلتر الخلفي شهرياً'),
    isNew: false,
    isFeatured: false,
    unit: 'قطعة',
    stock: 13,
    createdAt: '2026-03-19',
  },
  {
    id: 'p10',
    slug: 'samsung-fridge-4d',
    name: 'ثلاجة سامسونج أربعة أبواب 500 لتر',
    type: 'ثلاجة أربعة أبواب',
    categoryId: 'fridge',
    description: 'ثلاجة سايد باي سايد بفصل بين الثلاجة والفريزر ودرج خضار بمرونة تنظيم، مع تبريد سريع وتحكم دقيق في درجة الحرارة.',
    price: 1780000,
    image: 'products/samsung-fridge-4d.webp',
    images: ['products/samsung-fridge-4d.webp', 'products/fridge-gallery-1.webp', 'products/fridge-gallery-2.webp'],
    colors: [
      color('steel', 'ستيل', '#b9bec3'),
      color('black', 'أسود', '#1b1b1e'),
    ],
    specs: {
      brand: 'سامسونج',
      power: '0.9 ك.و.ه يومياً',
      capacity: '500 لتر',
      size: '83 × 178 × 72 سم',
      weight: '98 كجم',
      warranty: 'سنتان',
      finish: 'ستيل مقاوم للبصمات',
      use: 'عائلات من 5 أفراد فأكثر',
    },
    faqs: faqs('0.9 ك.و.ه يومياً بتصنيف كفاءة A+', 'سنتان شاملة، وعشر سنوات على محرك التبريد', 'عائلات كبيرة تحتاج مساحة تخزين للحوم والخضار', 'تنظيف الرفوف بمرطّب خفيف وترك مسافة 5 سم من الحائط لتدوير الهواء'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 5,
    createdAt: '2026-06-25',
  },
  {
    id: 'p11',
    slug: 'lg-fridge-2d',
    name: 'ثلاجة إل جي بابين 400 لتر',
    type: 'ثلاجة بابين',
    categoryId: 'fridge',
    description: 'ثلاجة بابين بوحدة تبريد Line Cooling توفر توزيعاً متواضعاً للحرارة، مع فريزر علوي سهل الوصول.',
    price: 1120000,
    image: 'products/lg-fridge-2d.webp',
    images: ['products/lg-fridge-2d.webp', 'products/fridge-gallery-2.webp', 'products/fridge-gallery-1.webp'],
    colors: [
      color('steel', 'ستيل', '#c0c4c7'),
      color('white', 'أبيض', '#f0f0f0'),
    ],
    specs: {
      brand: 'إل جي',
      power: '0.75 ك.و.ه يومياً',
      capacity: '400 لتر',
      size: '70 × 170 × 68 سم',
      weight: '76 كجم',
      warranty: 'سنتان',
      finish: 'ستيل أو أبيض لامع',
      use: 'عائلات من 4 أفراد',
    },
    faqs: faqs('0.75 ك.و.ه يومياً بتصنيف كفاءة A++', 'سنتان شاملة، وعشر سنوات على محرك التبريد', 'عائلات من أربعة أفراد مع مساحة فريزر مريحة', 'تنظيف مجرى التصريف الخلفي كل شهر ومنع تكدّس العناصر الجافة'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 7,
    createdAt: '2026-05-03',
  },
  {
    id: 'p12',
    slug: 'toshiba-fridge-300',
    name: 'ثلاجة توشيبا بابين 300 لتر',
    type: 'ثلاجة بابين',
    categoryId: 'fridge',
    description: 'ثلاجة متوسطة الحجم بفريزر سفلي وتقنيات تبريد تساعد على توازن الحرارة، مناسبة للأسر المتوسطة.',
    price: 795000,
    image: 'products/toshiba-fridge-300.webp',
    images: ['products/toshiba-fridge-300.webp', 'products/fridge-gallery-1.webp', 'products/fridge-gallery-2.webp'],
    colors: [
      color('silver', 'فضي', '#cfd2d5'),
      color('white', 'أبيض', '#eeeeee'),
    ],
    specs: {
      brand: 'توشيبا',
      power: '0.65 ك.و.ه يومياً',
      capacity: '300 لتر',
      size: '60 × 165 × 62 سم',
      weight: '61 كجم',
      warranty: 'سنة كاملة',
      finish: 'فضي مطفي',
      use: 'الأسر المتوسطة',
    },
    faqs: faqs('0.65 ك.و.ه يومياً بتصنيف كفاءة A+', 'سنة كاملة على قطع الغيار', 'الأسر من ثلاثة إلى أربعة أفراد', 'تباعد الأغذية عن جدران الثلاجة وترك مساحة للتهوية بين الأرفف'),
    isNew: true,
    isFeatured: false,
    unit: 'قطعة',
    stock: 9,
    createdAt: '2026-09-02',
  },
  {
    id: 'p13',
    slug: 'philips-kettle-17',
    name: 'غلاية فيليبس 1.7 لتر',
    type: 'غلاية كهربائية',
    categoryId: 'kitchen',
    description: 'غلاية سريعة التسخين بقاعدة قابلة للدوران وفلتر ترسبات، مع فاصل تشغيل آمن ومؤشر مضيء.',
    price: 45000,
    image: 'products/philips-kettle-17.webp',
    images: ['products/philips-kettle-17.webp', 'products/kitchen-gallery-1.webp', 'products/kitchen-gallery-2.webp'],
    colors: [
      color('steel', 'ستيل', '#c6cacc'),
      color('black', 'أسود', '#1c1c1f'),
    ],
    specs: {
      brand: 'فيليبس',
      power: '2200 واط',
      capacity: '1.7 لتر',
      size: '24 × 17 × 25 سم',
      weight: '1.2 كجم',
      warranty: 'سنة كاملة',
      finish: 'ستيل لامع',
      use: 'غلي الماء للشاي والقهوة',
    },
    faqs: faqs('2200 واط، وتغلق تلقائياً عند الغليان', 'سنة كاملة على قطع الغيار', 'المنزل والمكاتب لغلي الماء بسرعة', 'إزالة الترسبات كل شهرين بمحلول خل وماء دافئ وغسل الفلتر بانتظام'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 25,
    createdAt: '2026-08-14',
  },
  {
    id: 'p14',
    slug: 'oster-blender-14',
    name: 'خلاط أوستر 1.4 لتر',
    type: 'خلاط مطبخ',
    categoryId: 'kitchen',
    description: 'خلاط بقدرات 600 واط وسرعة متعددة مع وعاء زجاجي متين وشفرات ستانلس ستيل لخلط العصائر والمخبوزات.',
    price: 78000,
    image: 'products/oster-blender-14.webp',
    images: ['products/oster-blender-14.webp', 'products/kitchen-gallery-2.webp', 'products/kitchen-gallery-1.webp'],
    colors: [
      color('white', 'أبيض', '#f2f2f2'),
      color('red', 'أحمر', '#b02a2a'),
    ],
    specs: {
      brand: 'أوستر',
      power: '600 واط',
      capacity: '1.4 لتر',
      size: '38 × 20 × 20 سم',
      weight: '2.6 كجم',
      warranty: 'سنة كاملة',
      finish: 'قاعدة بلاستيكية مع وعاء زجاجي',
      use: 'خلط العصائر والشوربات والصلصات',
    },
    faqs: faqs('600 واط أثناء التشغيل', 'سنة كاملة على المحرك وقطع الغيار', 'تحضير العصائر والشوربات والخلط اليومي', 'غسل الوعاء بعد كل استخدام وتجنّب الخلط بالمواد الجافة القاسية'),
    isNew: false,
    isFeatured: false,
    unit: 'قطعة',
    stock: 18,
    createdAt: '2026-07-20',
  },
  {
    id: 'p15',
    slug: 'sharp-oven-35',
    name: 'فرن شارب ميكروويف 35 لتر',
    type: 'ميكروويف',
    categoryId: 'kitchen',
    description: 'فرن ميكروويف بسعة كبيرة ومشواة دوّارة، مع برامج إعداد سريع وشاشة أنيقة وسهلة التنظيف.',
    price: 235000,
    image: 'products/sharp-oven-35.webp',
    images: ['products/sharp-oven-35.webp', 'products/kitchen-gallery-1.webp', 'products/kitchen-gallery-2.webp'],
    colors: [
      color('black', 'أسود', '#18181b'),
      color('silver', 'فضي', '#c9ccd0'),
    ],
    specs: {
      brand: 'شارب',
      power: '900 واط',
      capacity: '35 لتر',
      size: '50 × 30 × 40 سم',
      weight: '14 كجم',
      warranty: 'سنة كاملة',
      finish: 'باب أسود مع مقابض معدنية',
      use: 'تسخين وطهي الأطعمة اليومية',
    },
    faqs: faqs('900 واط في الطهي و35 واط في التشغيل', 'سنة كاملة على قطع الغيار', 'تسخين الوجبات وإذابة المجمدات وطهي سريع', 'مسح الوعاء الداخلي بعد كل استخدام بقطعة قماش رطبة دون مواد كاوية'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 12,
    createdAt: '2026-06-05',
  },
  {
    id: 'p16',
    slug: 'cenner-ceiling-fan-16',
    name: 'مروحة سقف سينر 16 بوصة',
    type: 'مروحة سقف',
    categoryId: 'fans',
    description: 'مروحة سقف بهيكل معدني وشفرات واسعة توزّع الهواء في الغرف، مع سرعتين وريموت تحكم.',
    price: 68000,
    image: 'products/cenner-ceiling-fan-16.webp',
    images: ['products/cenner-ceiling-fan-16.webp', 'products/fans-gallery-1.webp', 'products/fans-gallery-2.webp'],
    colors: [
      color('walnut', 'جوزي', '#6b4a33'),
      color('white', 'أبيض', '#eeeeee'),
    ],
    specs: {
      brand: 'سينر',
      power: '65 واط',
      capacity: '16 بوصة (41 سم)',
      size: '41 × 41 × 34 سم',
      weight: '4.3 كجم',
      warranty: 'سنة كاملة',
      finish: 'طلاء جوزي أو أبيض',
      use: 'غرف النوم والمعيشة',
    },
    faqs: faqs('65 واط فقط، أخف استهلاكاً من المكيف', 'سنة كاملة على المحرك', 'تبريد الغرف الصغيرة والمتوسطة وتوزيع الهواء', 'مسح الشفرات أسبوعياً وشدّ التثبيت بعد أول شهر من التركيب'),
    isNew: false,
    isFeatured: true,
    unit: 'قطعة',
    stock: 22,
    createdAt: '2026-04-27',
  },
  {
    id: 'p17',
    slug: 'jetek-stand-fan-40',
    name: 'مروحة عمودية جيتك 40 سم',
    type: 'مروحة عمودية',
    categoryId: 'fans',
    description: 'مروحة عمودية بقاعدة ثابتة وثلاث سرعات مع مؤقت زمني، مناسبة لغرف العمل والمجالس.',
    price: 45000,
    image: 'products/jetek-stand-fan-40.webp',
    images: ['products/jetek-stand-fan-40.webp', 'products/fans-gallery-2.webp', 'products/fans-gallery-1.webp'],
    colors: [
      color('white', 'أبيض', '#f1f1f1'),
      color('gray', 'رمادي', '#9aa0a6'),
    ],
    specs: {
      brand: 'جيتك',
      power: '55 واط',
      capacity: '40 سم قطر الشفرة',
      size: '40 × 125 × 40 سم',
      weight: '3.1 كجم',
      warranty: 'سنة كاملة',
      finish: 'بلاستيك أبيض',
      use: 'الغرف والمجالس والمكاتب',
    },
    faqs: faqs('55 واط في أعلى سرعة', 'سنة كاملة على المحرك', 'تبريد مباشر في الغرف والمكاتب', 'فك الشفرة ومسحها كل شهر وفحص ثبات القاعدة'),
    isNew: false,
    isFeatured: false,
    unit: 'قطعة',
    stock: 30,
    createdAt: '2026-05-30',
  },
  {
    id: 'p18',
    slug: 'junray-heater-2000',
    name: 'دفاية كهربائية جونراي 2000 واط',
    type: 'دفاية كهربائية',
    categoryId: 'fans',
    description: 'دفاية زجاجية بعدين حراريين وحماية ضد السقوط والحرارة الزائدة، تدفّئ الغرفة خلال دقائق.',
    price: 58000,
    image: 'products/junray-heater-2000.webp',
    images: ['products/junray-heater-2000.webp', 'products/fans-gallery-1.webp', 'products/fans-gallery-2.webp'],
    colors: [
      color('black', 'أسود', '#1f1f22'),
    ],
    specs: {
      brand: 'جونراي',
      power: '2000 واط',
      capacity: 'تدفئة حتى 20 م²',
      size: '24 × 62 × 18 سم',
      weight: '3.8 كجم',
      warranty: 'سنة كاملة',
      finish: 'زجاج أسود مع إطار معدني',
      use: 'تدفئة المكاتب والغرف الصغيرة',
    },
    faqs: faqs('2000 واط في الوضع القوي و1000 واط في الوضع المعتدل', 'سنة كاملة على قطع الغيار والحماية الآلية', 'تدفئة الغرف الصغيرة والمكاتب حتى 20 متر مربع', 'تنظيف شبكة الدخول الهوائي شهرياً ولا تغطي الجهاز أثناء التشغيل'),
    isNew: true,
    isFeatured: true,
    unit: 'قطعة',
    stock: 16,
    createdAt: '2026-09-15',
  },
]

export const fallbackRoutes: SiteRoute[] = [
  { id: 'home', label: 'الرئيسية', path: '/', header: true },
  { id: 'catalog', label: 'المنتجات', path: '/catalog', header: true },
  { id: 'new', label: 'وصل حديثاً', path: '/catalog?sort=newest', header: true },
  { id: 'favorites', label: 'المفضلة', path: '/favorites', header: false },
  { id: 'about', label: 'من نحن', path: '/about', header: true },
  { id: 'guide', label: 'دليل الأجهزة', path: '/fabric-guide', header: true },
  { id: 'contact', label: 'تواصلي معنا', path: '/contact', header: false },
  { id: 'tracking', label: 'تتبع الطلب', path: '/order-tracking', header: false },
  { id: 'policies', label: 'السياسات', path: '/policies', header: false },
]

export const governorates = [
  'بغداد', 'البصرة', 'نينوى', 'أربيل', 'النجف', 'كربلاء', 'الأنبار', 'ديالى',
  'كركوك', 'صلاح الدين', 'واسط', 'بابل', 'ذي قار', 'المثنى', 'القادسية', 'دهوك', 'السليمانية',
]

export const guideQuestions: ProductFaq[] = [
  { question: 'كيف أختار مقاس الشاشة المناسب؟', answer: 'القاعدة البسيطة أن تبعد عن الشاشة ثلاثة أضعاف ارتفاعها. شاشة 55 بوصة تناسب مسافة المشاهدة بين 2.5 و3 أمتار في غرفة المعيشة، وشاشة 43 بوصة مناسبة للغرف الأصغر والمسافات الأقصر.' },
  { question: 'ما الفرق بين الإنفرتر والسبليت العادي؟', answer: 'الإنفرتر يغيّر سرعة الضاغط بدل تشغيله وإيقافه المتكرر، فتبقى الحرارة ثابتة ويقلّ الاستهلاك بنحو 30 إلى 40 في المئة. السبليت العادي أرخص في الشراء لكنه أعلى في الاستهلاك على المدى الطويل.' },
  { question: 'كيف أحسب قدرة المكيف المناسبة لغرفتي؟', answer: 'اقسم مساحة الغرفة على 10 لتعرف عدد آلاف الوحدة المطلوب تقريبياً. غرفة 20 متر مربع تحتاج نحو 2000 وحدة تقريباً. زد قدرة إذا كانت الغرفة جنوبية أو فيها شبابيك كبيرة.' },
  { question: 'كم كيلوغراماً أحتاج للغسالة؟', answer: 'الأسرة من ثلاثة أفراد تكتفي بـ6 كجم، وأربعة إلى ستة أفراد تحتاج 8 كجم. الاختيار الأكبر يوفر عليك دورات غسيل إضافية لكنه يستهلك ماءاً وطاقة أكثر في كل دورة.' },
  { question: 'ما معنى استهلاك الطاقة A+++؟', answer: 'كلما اقتربت التصنيفة من A كانت أجهزة أقل استهلاكاً للكهرباء عند المقارنة بالمقاس نفسه. الفرق بين A وC قد يبلغ مئات الدينارات سنوياً على الجهاز القوي كالثلاجة والمكيف.' },
]

export const trustItems = [
  { title: 'توصيل لكل العراق', description: 'جميع المحافظات', icon: 'truck' },
  { title: 'شحن دولي', description: 'عند توفر الشحنة', icon: 'globe' },
  { title: 'دعم عبر واتساب', description: 'قبل وبعد الطلب', icon: 'message' },
  { title: 'ضمان معتمد', description: 'ضمان واضح لكل جهاز', icon: 'check' },
] as const

export const homeStory = {
  title: 'أجهزة منزلية تستحق الثقة',
  text: 'فيلا هوم متجر عراقي يجمع الأجهزة المنزلية المختارة مع مواصفات واضحة وصور صادقة، لتجد الجهاز المناسب لبيتك من دون تخمين أو مبالغة.',
}
